### PR TITLE
Revert "Update README.md"

### PR DESCRIPTION
**Pull request by revieweradmin**
Reverts revieworg/review-repo#2

### CODE REVIEW

**Comment by revieweradmin** [comment]
@revieweruser I am reverting this PR as part of testing. Take a look!

**Comment by revieweradmin** [comment]
@revieweruser HELLO!

**Comment by revieweradmin** [comment]
@revieweruser hello?

**Comment by revieweruser** [comment]
@revieweradmin Looking!

**Comment by revieweruser** [comment]
+1

**Comment by revieweruser** [comment]
@revieweradmin hello?

**Comment by revieweradmin** [comment]
hey @revieweruser this is fine

**Pull request merged**
